# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

In [ ]:
print(f"Number of axes in matrix A: {A.ndim}")
print(f"Shape of matrix A: {A.shape}")
print(f"Size of matrix A (number of elements): {A.size}")
print(f"Data type of matrix A's elements: {A.dtype}")

Number of axes: 2
Shape of matrix: (3, 5)
Size of matrix (number of elements): 15
Data type of matrix elements: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [18]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Matrix B:")
print(B)
print()
print("Matrix C:")
print(C)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [23]:
print("Elementwise subtraction B - C :")
print(B - C)
print()

print("Elementwise multiplication B * C:")
print(B * C)
print()

print("Matrix multiplication B @ C:")
print(B @ C)

Elementwise subtraction B - C :
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication B * C:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication B @ C:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
print("B:")
print(B)
print()

# Exponentiate each number elementwise (use the np.exp function).
print("np.exp(B)")
print(np.exp(B))
print()


# Calculate the minimum value in the whole matrix. 
print("the minimum value in the whole matrix")
print(np.min(B))
print()

#Calculcate the minimum value in each row. 
print("The minimum value in each row:")
print(np.min(B, axis=1))
print()

# Calculcate the minimum value in each column. 
print("The minimum value in each column:")
print(np.min(B, axis=0))
print()


# Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
(idx_row, idx_col) = np.unravel_index(np.argmin(B), B.shape)
print(f"The index smallest element in the matrix is in row {idx_row}, and col {idx_col}")
print(f"({idx_row}, {idx_col})")
print()

# Find the index value for the minimum value in each row (hint: use np.argmin).
print("The index value for the minimum value in each row:")
print(np.argmin(B, axis=1))
print()

B:
[[12 23  9]
 [ 1  3 11]
 [35  2 22]
 [13  8  7]]

np.exp(B)
[[1.62754791e+05 9.74480345e+09 8.10308393e+03]
 [2.71828183e+00 2.00855369e+01 5.98741417e+04]
 [1.58601345e+15 7.38905610e+00 3.58491285e+09]
 [4.42413392e+05 2.98095799e+03 1.09663316e+03]]

the minimum value in the whole matrix
1

The minimum value in each row:
[9 1 2 7]

The minimum value in each column:
[1 2 7]

The index smallest element in the matrix is in row 1, and col 0
(1, 0)

The index value for the minimum value in each row:
[2 0 1 2]

The sum for all elements:
146
The mean for each column:
[15.25  9.   12.25]
The median for each column:
[12.5  5.5 10. ]


In [55]:
# Calculate the sum for all elements.
print("The sum for all elements:")
print(np.sum(B))
print()

# Calculate the mean for each column. 
print("The mean for each column:")
print(np.mean(B, axis=0))
print()

# Calculate the median for each column. 
print("The median for each column:")
print(np.median(B, axis=0))
print()


The sum for all elements:
146

The mean for each column:
[15.25  9.   12.25]

The median for each column:
[12.5  5.5 10. ]



In [56]:
# Find the index value for the minimum value in each row (hint: use np.argmin).
print("The index of the smallest element in the matrix in each row:")
result = np.argmin(B, axis=1)
print(result)
print()

# Skriv ut resultatet
for row_index, col_index in enumerate(min_element_is_in_column):
    print(f"In row {row_index} the smallest element has column index {col_index}  i.e.  ({row_index}, {col_index})")

# Calculate the sum for all elements.
# Calculate the mean for each column. 
# Calculate the median for each column. 



The index of the smallest element in the matrix in each row:
[2 0 1 2]

In row 0 the smallest element has column index 2  i.e.  (0, 2)
In row 1 the smallest element has column index 0  i.e.  (1, 0)
In row 2 the smallest element has column index 1  i.e.  (2, 1)
In row 3 the smallest element has column index 2  i.e.  (3, 2)


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [68]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [69]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# You get an array of elements on that index. If it is the second last axis the array will have only one dimension
# otherwise you will get a matrix

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [70]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [71]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [72]:
np.ravel(A)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)               # render a range (a) from 0 to 30 (not included)
b = a.reshape((2, 3, -1))       # take the values in a and produce a martrix (in this case with 3 axis)
                                # the '-1' in this case means that the 3:rd axis will get "the rest" of the
                                # elements, i.e. numpy will calculate the size of the axis
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [75]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [76]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [83]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [ ]:

def add_mult_matrices(M1, M2, operation):
    # Validate that both arguments ar of numpy.ndarray type
    if not isinstance(M1, np.ndarray):
        raise TypeError("M1 must be of type numpy.ndarray")
    if not isinstance(M2, np.ndarray):
        raise TypeError("M2 must be of type numpy.ndarray")

    # Check that operation is on of 'add' or 'multiply'
    if operation not in ('add', 'multiply'):
        raise ValueError("The operation argument must be either 'add' or 'multiply'")

    if operation == 'add':
        # Validate that the matrices have the same shape
        if M1.shape != M2.shape:
            raise ValueError("For addition, matrices must have the same shape")
        return M1 + M2

    elif operation == 'multiply':
        # Check that the number of columns in the first matrix is
        # the same as the number of rows in the second
        if M1.shape[1] != M2.shape[0]:
            raise ValueError("For multiplication, the number of columns in M1 must equal the number of rows in M2")
        return M1 @ M2

A = np.arange(10).reshape(2,-1)
AT = np.transpose(A)
B = np.arange(10, 20).reshape(2,-1)
C = np.arange(10).reshape(-1,2)

print(A)
print()
print(B)
print()
print(C)
print()

print("ops = add")
print(add_mult_matrices(A, B, "add"))
print()

print("ops = multiply")
print(add_mult_matrices(A, AT, "multiply"))
print()

# print("ops = subtract (bad option)")
# print(add_mult_matrices(A, B, "subtract"))
# print()

# print("A C different shapes, ops = add")
# print(add_mult_matrices(A, C, "add"))
# print()

# print("ops = multiply (not matching rows and columns)")
# print(add_mult_matrices(A, B, "multiply"))
# print()



[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

ops = add
[[10 12 14 16 18]
 [20 22 24 26 28]]

ops = multiply
[[ 30  80]
 [ 80 255]]



### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [ ]:
### UPPGITER 10.1.1
x = np.array([4,3]).reshape(1, -1) # Make a row vector out of an array

print("\nx =")
print(x)

print("\n(a)")
print(np.ndim(x))

print("\n(b)")
print(5*x)

print("\n(c)")
print(3*x)

print("\n(d)")
print(5*x + 3*x)

print("\n(e)")
print(8*x)

print("\n(f)")
print(4*x - x)

print("\n(g)")
print(np.transpose(x))
print(np.ndim(np.transpose(x)))

print("\n(h)")
print(x + x.T)
print("Nej, inte matematiskt vektorerna måste ha identisk form. Men i numpy som använder 'broadcasting'är det tillåtet")

print("\n(i)")
print(np.linalg.norm(x))



x =
[[4 3]]

(a)
2

(b)
[[20 15]]

(c)
[[12  9]]

(d)
[[32 24]]

(e)
[[32 24]]

(f)
[[12  9]]

(g)
[[4]
 [3]]
2

(h)
[[8 7]
 [7 6]]
ja, i numpy som använder 'broadcasting', men matematiskt måste vektorerna ha identisk form

(i)
5.0


In [184]:
### UPGIFT 10.1.2

v = np.array([3, 7, 0, 11]).reshape(-1, 1) # Make a column vector out of an array
print("\n(a)")
print(np.ndim(v))

print("\n(b)")
print(2*v)

print("\n(c)")
print(5*v + 2*v)

print("\n(d)")
print(4*v - 2*v)

print("\n(e)")
print(v.T)
print(np.ndim(v.T))

print("\n(f)")
print(np.linalg.norm(v))


(a)
2

(b)
[[ 6]
 [14]
 [ 0]
 [22]]

(c)
[[21]
 [49]
 [ 0]
 [77]]

(d)
[[ 6]
 [14]
 [ 0]
 [22]]

(e)
[[ 3  7  0 11]]
2

(f)
13.379088160259652


In [185]:
### UPPGIFT 10.1.3
v1 = np.array([4, 3, 1, 5]).reshape(1, -1) # Make a row vector out of an array
v2 = np.array([2, 3, 1, 1]).reshape(1, -1) # Make a row vector out of an array

print("\nlength v1")
print(np.linalg.norm(v1))

print("\nlength v2 - v1 (i.e. distance between v1 and v2)")
print(np.linalg.norm(v2 - v1))


length v1
7.14142842854285

length v2 - v1 (i.e. distance between v1 and v2)
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [ ]:
def matrixmath(M1, M2, operation):
    # Validate that both arguments ar of numpy.ndarray type
    if not isinstance(M1, np.ndarray):
        print("M1 must be of type numpy.ndarray")
        return
    if not isinstance(M2, np.ndarray):
        print("M2 must be of type numpy.ndarray")
        return

    # Check that operation is on of 'add' or 'multiply'
    if operation not in ('+', '-', '*', '@'):
        print("The operation argument must be one of '+', '-', '*', '@'")
        return

    if operation == '+':
        # Validate that the matrices have the same shape
        if M1.shape != M2.shape:
            print("For addition, matrices must have the same shape")
            return
        return M1 + M2
    
    if operation == '-':
        # Validate that the matrices have the same shape
        if M1.shape != M2.shape:
            print("For subtrection, matrices must have the same shape")
            return
        return M1 - M2   
     
    if operation == '*':
        # Multiplication element by element requires that the matrices have the same shape
        if M1.shape != M2.shape:
            print("For multiplication element by element, matrices must have the same shape")
            return
        return M1 * M2
    
    elif operation == '@':
        # Check that the number of columns in the first matrix is
        # the same as the number of rows in the second
        if M1.shape[1] != M2.shape[0]:
            print("For multiplication, the number of columns in M1 must equal the number of rows in M2")
            return
        return M1 @ M2

In [ ]:
### UPGIFTERNA 10.2.1 a-l
def same_shape(M1, M2):
    if not (isinstance(M1, np.ndarray) and isinstance(M2, np.ndarray)):
        return False
    
    if np.shape(M1) == np.shape(M2):
        return True
    
    return False

def multiplication_allowed(M1, M2):
    ### num cols in M1 should be equal to num rows in M2 to be true
    if not (isinstance(M1, np.ndarray) and isinstance(M2, np.ndarray)):
        return False

    if M1.shape[1] != M2.shape[0]:
        return False
    
    return True

### Define all the matrices
A = np.array([2, 1, -1, 1, -1, 1]).reshape(2,3)
B = np.array([4, -2, 1, 2, -4, -2]).reshape(2,3)
C = np.array([1, 2, 2, 1]).reshape(2,2)
D = np.array([3, 4, 4, 3]).reshape(2,2)
E = np.array([[1], [2]])
I = np.array([1, 0, 0, 1]).reshape(2,2)

print("A")
print(A)
print("B")
print(B)
print("C")
print(C)
print("D")
print(D)
print("E")
print(E)
print("I")
print(I)
print("\n(a) ------------------- 2A")
print(2*A)
print("\n(b) ------------------- B - 2A")
A2 = 2 * A
if same_shape(B, A2):
    print(matrixmath(B, A2, "-"))

print("\n(c) ------------------- 3C - 2E")
C3 = 3 * C
E2 = 2 * E
if same_shape(C3, E2):
    print(matrixmath(C3, E2, "-"))
else:
    print("Operation not allowed")

print("\n(d) ------------------- 2D - 3C")
D2 = 2 * D
if same_shape(D2, C3):
    print(matrixmath(D2, C3, "-"))
else:
    print("Operation not allowed")

print("\n(e) ------------------- DT + 2D")
if same_shape(np.transpose(D), D2):
    print(matrixmath(np.transpose(D), D2, "+"))
else:
    print("Operation not allowed")

print("\n(f) ------------------- 2CT - 2DT")
if same_shape(2*np.transpose(C), 2*np.transpose(D)):
    print(matrixmath(2*np.transpose(C), 2*np.transpose(D), "-"))
else:
    print("Operation not allowed")


print("\n(g) ------------------- AT - B")
if same_shape(np.transpose(A), B):
    print(matrixmath(np.transpose(A), B, "-"))
else:
    print("Operation not allowed")

print("\n(h) ------------------- AC")
if multiplication_allowed(A, C):
    print(matrixmath(A, C, "@"))
else:
    print("Operation not allowed")

print("\n(i) ------------------- CD")
if multiplication_allowed(C, D):
    print(matrixmath(C, D, "@"))
else:
    print("Operation not allowed")

print("\n(j) ------------------- CB")
if multiplication_allowed(C, B):
    print(matrixmath(C, B, "@"))
else:
    print("Operation not allowed")

print("\n(k) ------------------- CI")
if multiplication_allowed(C, I):
    print(matrixmath(C, I, "@"))
else:
    print("Operation not allowed")

print("\n(l) ------------------- ABT")
if multiplication_allowed(A, np.transpose(B)):
    print(matrixmath(A, np.transpose(B), "@"))
else:
    print("Operation not allowed")






True
A
[[ 2  1 -1]
 [ 1 -1  1]]
B
[[ 4 -2  1]
 [ 2 -4 -2]]
C
[[1 2]
 [2 1]]
D
[[3 4]
 [4 3]]
E
[[1]
 [2]]
I
[[1 0]
 [0 1]]

(a) ------------------- 2A
[[ 4  2 -2]
 [ 2 -2  2]]

(b) ------------------- B - 2A
[[ 0 -4  3]
 [ 0 -2 -4]]

(c) ------------------- 3C - 2E
Operation not allowed

(d) ------------------- 2D - 3C
[[3 2]
 [2 3]]

(e) ------------------- DT + 2D
[[ 9 12]
 [12  9]]

(f) ------------------- 2CT - 2DT
[[-4 -4]
 [-4 -4]]

(g) ------------------- AT - B
Operation not allowed

(h) ------------------- AC
Operation not allowed

(i) ------------------- CD
[[11 10]
 [10 11]]

(j) ------------------- CB
[[  8 -10  -3]
 [ 10  -8   0]]

(k) ------------------- CI
[[1 2]
 [2 1]]

(l) ------------------- ABT
[[5 2]
 [7 4]]


In [ ]:
### UPPGIFT 10.2.2

A = np.array([2, 3, 4, 5, 4, 1]).reshape(2, 3)

print("\nA")
print(A)

AT = np.transpose(A)
print("\nAAT")
print(A@AT)



A
[[2 3 4]
 [5 4 1]]

AAT
[[29 26]
 [26 42]]
[[29 26]
 [26 42]]


In [196]:
### UPPGIFT 10.2.3

A = np.array([1, 2, 2, 4]).reshape(2, 2)
B = np.array([2, 1, 1, 3]).reshape(2, 2)
C = np.array([4, 3, 0, 2]).reshape(2, 2)

print("\nAB")
print(A@B)

print("\nAC")
print(A@C)

print("\nAB = AC")
print(np.array_equal(A@B, A@C))

print("\nB = C")
print(np.array_equal(B, C))


AB
[[ 4  7]
 [ 8 14]]

AC
[[ 4  7]
 [ 8 14]]

AB = AC
True

B = C
False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [213]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)


[0 1 2 3]
[2 3]


In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)


None
[0 1 2 3]
[  0   1   2 100]
[  2 100]


In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)